config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :crops do
    collection do
      get :procedure_details
    end
  end
  mount Ckeditor::Engine => '/ckeditor'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :crops
end

app/models/ckeditor/asset.rb
# frozen_string_literal: true

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
# frozen_string_literal: true

class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# frozen_string_literal: true

class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/crop.rb
class Crop < ApplicationRecord
  has_many :procedures
  belongs_to :category
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  has_many :procedure_details
  belongs_to :crop
end

app/models/procedure_detail.rb
class ProcedureDetail < ApplicationRecord
  belongs_to :procedure
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :load_init_data

  def load_init_data
    @categories = Category.all
  end
end

app/controllers/crops_controller.rb
class CropsController < ApplicationController
  def index
    category = Category.find(params[:category])
    @crops = category.crops
  end

  def show
    @crop = Crop.find(params[:id])
  end

  def procedure_details
    @procedure = Procedure.find(params[:details])
    @details = @procedure.procedure_details.first
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crops_helper.rb
module CropsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/procedure_details/_procedure_details_form.html.erb
<%= javascript_include_tag  Ckeditor.cdn_url, 'data-turbolinks-track': 'reload' %>

<div class="food-wraper">
  <%= semantic_form_for [:admin, @procedure_detail] do |f| %>
    <%= f.semantic_errors *f.object.errors.keys %>
    <%= f.inputs do %>
      <%= f.input :procedure_id, :as => :select, :collection => Procedure.all.collect {|p| [p.title, p.id]} %>
      <%= f.cktext_area :details, cols: 40, ckeditor: { uiColor: '#AADC6E', toolbar: 'mini' } %>
    <% end %>
    <%= f.actions %>
  <% end %>
</div>

app/views/crops/_crops_procedure.html.erb
<div class="col-lg-4">
  <div class="mailbox-menu">
    <ul class="list-unstyled">
      <% @crop.procedures.each do |procedure| %>
        <li>
          <%= link_to procedure_details_crops_path(details: procedure.id), remote: true do %>
            <%= procedure.title %>
            habib
          <% end %>
        </li>
      <% end %>
<!--      <li><a href="#" class="active"><i class="icon-inbox"></i>BD Rice 01</a></li>-->
<!--      <li><a href="#"><i class="icon-send"></i>BD Rice Disease 3</a></li>-->
<!--      <li><a href="#"><i class="icon-mail_outline"></i>BD Rice Harvesting</a></li>-->
<!--      <li><a href="#"><i class="icon-error"></i>Bd Rice Land</a></li>-->
      <li class="divider"></li>
    </ul>
  </div>
</div>

<div class="col-lg-7">
  <div class="mail-container">
    <div class="mail-text" id="procedure-details"></div>
  </div>
</div>

app/views/crops/_details.html.erb
<%= raw @details.details %>

app/views/crops/index.html.erb
<div id="main-wrapper">
  <div class="row">
    <div class="col-lg-8">
      <div class="mailbox-options d-flex align-items-center">
        <% @crops.each do |crop| %>
          <%= link_to crop.name, crop_path(crop), class: 'btn btn-primary m-r-xxs', remote: true%>
        <% end %>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="mailbox-search">
        <form>
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search mailbox" aria-label="Example text with button addon" aria-describedby="button-addon1">
            <div class="input-group-append">
              <button class="btn btn-primary" type="button" id="button-addon1">Search</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="divider"></div>
</div>
<div class="row" id="crops_procedure">

</div><!-- Main Wrapper -->

app/views/crops/procedure_details.js.erb
$("#procedure-details").html("<%=escape_javascript(render 'details').html_safe%>")

app/views/crops/show.js.erb
$("#crops_procedure").html("<%= escape_javascript(render 'crops_procedure').html_safe %>")

app/views/home/index.html.erb
<h2 style="margin: 100px 0 0 0;"><b>Welcome to Web base Agriculture information and Problem Solution!</b></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AgricultureInfo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag  Ckeditor.cdn_url, 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="page-container">
  <!-- Page Sidebar -->
  <%= render 'shared/sidebar' %>
  <%= render 'shared/setting_sidebar' %>

  <div class="settings-overlay"></div>
  <!-- Page Content -->
  <div class="page-content">
    <%= render 'shared/secondary_sidebar' %>
    <!-- Page Header -->
    <%= render 'shared/header'%>
    <!-- /Page Header -->
    <!-- Page Inner -->
    <div class="page-inner no-page-title">
      <%= yield %>
    </div><!-- /Page Inner -->
    <%= render 'shared/chat' %>
    <%= render 'shared/right_sidebar' %>
  </div><!-- /Page Content -->
  </div><!-- /Page Container -->
  <script src="//code.tidio.co/ig5pcyldq53fep3qf1an6rmyqos69pdz.js" async> </script>
  </body>
</html>

app/views/shared/_chat.html.erb
<div class="page-right-sidebar" id="main-right-sidebar">
  <div class="page-right-sidebar-inner">
    <div class="right-sidebar-top">
      <span class="chat-header">Chat</span>
      <a href="javascript:void(0)" class="right-sidebar-toggle right-sidebar-close" data-sidebar-id="main-right-sidebar"><i class="icon-close"></i></a>
    </div>
    <div class="right-sidebar-content">
      <!-- Tab panes -->
      <div class="chat-list">
        <span class="chat-title">Recent</span>
        <a href="javascript:void(0);" class="right-sidebar-toggle chat-item unread" data-sidebar-id="chat-right-sidebar">
          <div class="user-avatar">
            <%= image_tag 'avatars/avatar1.png', alt: "" %>
          </div>
          <div class="chat-info">
            <span class="chat-author">David</span>
            <span class="chat-text">Hello there!</span>
            <span class="chat-time">16:20</span>
          </div>
        </a>
        <a href="javascript:void(0);" class="right-sidebar-toggle chat-item unread active-user" data-sidebar-id="chat-right-sidebar">
          <div class="user-avatar">
            <%= image_tag 'avatars/avatar2.png', alt: "" %>
          </div>
          <div class="chat-info">
            <span class="chat-author">Bob</span>
            <span class="chat-text">Hello there!</span>
            <span class="chat-time">11:34</span>
          </div>
        </a>
      </div>
      <div class="chat-list">
        <span class="chat-title">Older</span>
        <a href="javascript:void(0);" class="right-sidebar-toggle chat-item" data-sidebar-id="chat-right-sidebar">
          <div class="user-avatar">
            <%= image_tag 'avatars/avatar3.png', alt: "" %>
          </div>
          <div class="chat-info">
            <span class="chat-author">Tom</span>
            <span class="chat-text">Hello there!</span>
            <span class="chat-time">2d</span>
          </div>
        </a>
        <a href="javascript:void(0);" class="right-sidebar-toggle chat-item active-user" data-sidebar-id="chat-right-sidebar">
          <div class="user-avatar">
            <%= image_tag 'avatars/avatar4.png', alt: "" %>
          </div>
          <div class="chat-info">
            <span class="chat-author">Anna</span>
            <span class="chat-text">Hello there!</span>
            <span class="chat-time">4d</span>
          </div>
        </a>
        <a href="javascript:void(0);" class="right-sidebar-toggle chat-item active-user" data-sidebar-id="chat-right-sidebar">
          <div class="user-avatar">
            <%= image_tag 'avatars/avatar5.png', alt: "" %>
          </div>
          <div class="chat-info">
            <span class="chat-author">Noah</span>
            <span class="chat-text">Hello there!</span>
            <span class="chat-time">&nbsp;</span>
          </div>
        </a>
        <a href="javascript:void(0);" class="load-more-messages" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Load More">•••</a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="page-header">
  <div class="search-form">
    <form action="#" method="GET">
      <div class="input-group">
        <input type="text" name="search" class="form-control search-input" placeholder="Type something...">
        <span class="input-group-btn">
                                    <button class="btn btn-default" id="close-search" type="button"><i class="icon-close"></i></button>
                                </span>
      </div>
    </form>
  </div>
  <nav class="navbar navbar-default navbar-expand-md">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <div class="logo-sm">
          <a href="javascript:void(0)" id="sidebar-toggle-button"><i class="fas fa-bars"></i></a>
          <a class="logo-box" href="index.html"><span>concept</span></a>
        </div>
        <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <i class="fas fa-angle-down"></i>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->

      <div class="collapse navbar-collapse justify-content-between" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav mr-auto">
          <li class="collapsed-sidebar-toggle-inv"><a href="javascript:void(0)" id="collapsed-sidebar-toggle-button"><i class="fas fa-bars"></i></a></li>


        </ul>
      </div><!-- /.navbar-collapse -->
      <ul class="nav navbar-nav">
        <li class="nav-item d-md-block"><a href="javascript:void(0)" class="right-sidebar-toggle" data-sidebar-id="main-right-sidebar"><i class="fas fa-envelope"></i></a></li>
        <li class="dropdown nav-item d-md-block">
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-bell"></i></a>
          <ul class="dropdown-menu dropdown-menu-right dropdown-lg dropdown-content">
            <li class="drop-title">Notifications<a href="#" class="drop-title-link"><i class="fas fa-angle-right"></i></a></li>
            <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 250px;"><li class="slimscroll dropdown-notifications" style="overflow: hidden; width: auto; height: 250px;">
              <ul class="list-unstyled dropdown-oc">
                <li>
                  <a href="#"><span class="notification-badge bg-info"><i class="fas fa-at"></i></span>
                    <span class="notification-info">
                                                                <span class="notification-info"><b>John Doe</b> mentioned you in a post "Update v1.5"</span>
                                                                <small class="notification-date">06:07</small>
                                                            </span></a>
                </li>
                <li>
                  <a href="#"><span class="notification-badge bg-danger"><i class="fas fa-bolt"></i></span>
                    <span class="notification-info">
                                                                <span class="notification-info">4 new special offers from the apps you follow!</span>
                                                                <small class="notification-date">Yesterday</small>
                                                            </span></a>
                </li>
                <li>
                  <a href="#"><span class="notification-badge bg-success"><i class="fas fa-bullhorn"></i></span>
                    <span class="notification-info">
                                                                <span class="notification-info">There is a meeting with <b>Ethan</b> in 15 minutes!</span>
                                                                <small class="notification-date">Yesterday</small>
                                                            </span></a>
                </li>
              </ul>
            </li><div class="slimScrollBar" style="background: rgb(204, 204, 204); width: 6px; position: absolute; top: 0px; opacity: 0.2; display: block; border-radius: 0px; z-index: 99; right: 0px; height: 239.464px;"></div><div class="slimScrollRail" style="width: 6px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 0px; background: rgb(51, 51, 51); opacity: 0.2; z-index: 90; right: 0px;"></div></div>
          </ul>
        </li>
        <li class="dropdown nav-item d-md-block">
          <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= image_tag 'avatars/avatar1.png', alt: "", class: 'rounded-circle' %>
          </a>
          <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <li><a href="#">Profile</a></li>
            <li><a href="#">Calendar</a></li>
            <li><a href="#"><span class="badge float-right badge-info">64</span>Messages</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Account Settings</a></li>
            <li><a href="#">Log Out</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.container-fluid -->
  </nav>
</div>

app/views/shared/_right_sidebar.html.erb
<div class="page-right-sidebar" id="chat-right-sidebar">
  <div class="page-right-sidebar-inner">
    <div class="right-sidebar-top">
      <div class="chat-top-info">
        <span class="chat-name">Noah</span>
        <span class="chat-state">2h ago</span>
      </div>
      <a href="javascript:void(0)" class="right-sidebar-toggle chat-sidebar-close float-right" data-sidebar-id="chat-right-sidebar"><i class="icon-keyboard_arrow_right"></i></a>
    </div>
    <div class="right-sidebar-content">
      <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 250px;"><div class="right-sidebar-chat slimscroll" style="overflow: hidden; width: auto; height: 250px;">
        <div class="chat-bubbles">
          <div class="chat-start-date">02/06/2017 5:58PM</div>
          <div class="chat-bubble them">
            <div class="chat-bubble-img-container">
              <%= image_tag 'avatars/avatar1.png', alt: "" %>
            </div>
            <div class="chat-bubble-text-container">
              <span class="chat-bubble-text">Hello</span>
            </div>
          </div>
          <div class="chat-bubble me">
            <div class="chat-bubble-text-container">
              <span class="chat-bubble-text">Hello!</span>
            </div>
          </div>
          <div class="chat-start-date">03/06/2017 4:22AM</div>
          <div class="chat-bubble me">
            <div class="chat-bubble-text-container">
              <span class="chat-bubble-text">lorem</span>
            </div>
          </div>
          <div class="chat-bubble them">
            <div class="chat-bubble-img-container">
              <%= image_tag 'avatars/avatar1.png', alt: "" %>
            </div>
            <div class="chat-bubble-text-container">
              <span class="chat-bubble-text">ipsum dolor sit amet</span>
            </div>
          </div>
        </div>
      </div><div class="slimScrollBar" style="background: rgb(204, 204, 204); width: 6px; position: absolute; top: 0px; opacity: 0.2; display: none; border-radius: 0px; z-index: 99; right: 0px; height: 556px;"></div><div class="slimScrollRail" style="width: 6px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 0px; background: rgb(51, 51, 51); opacity: 0.2; z-index: 90; right: 0px;"></div></div>
      <div class="chat-write">
        <form class="form-horizontal" action="javascript:void(0);">
          <input type="text" class="form-control" placeholder="Say something">
        </form>
      </div>
    </div>
  </div>
</div>

app/views/shared/_secondary_sidebar.html.erb
<div class="secondary-sidebar">
  <div class="secondary-sidebar-bar">
    <a href="#" class="logo-box">concept</a>
  </div>
  <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 100%;"><div class="secondary-sidebar-menu" style="overflow: hidden; width: auto; height: 100%;">
    <ul class="accordion-menu">
      <li>
        <a href="index.html">
          <i class="menu-icon icon-home4"></i><span>Crops data</span>
        </a>
      </li>

      <li class="active-page open">
        <a href="javascript:void(0)">
          <i class="menu-icon icon-apps"></i><span>Crops</span><i class="accordion-icon fas fa-angle-left"></i>
        </a>
        <ul class="sub-menu" style="display: block;">
          <% @categories.each do |category| %>
            <li class="animation">
              <%= link_to crops_path(category: category.id), class: 'active' do%>
                <%= category.name %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </li>

      <li class="active-page open">
        <a href="javascript:void(0)">
          <i class="menu-icon icon-apps"></i><span>Fisheries</span><i class="accordion-icon fas fa-angle-left"></i>
        </a>
        <ul class="sub-menu" style="display: block;">
          <li class="animation"><a href="" class="active">Cereal Crops</a></li>
          <li class="animation"><a href="app-todo.html">Tuber Crops</a></li>
          <li class="animation"><a href="app-contacts.html">Oilseed Crops</a></li>
          <li class="animation"><a href="app-profile.html">Pulse Crops</a></li>
        </ul>
      </li>

      <li class="active-page open">
        <a href="javascript:void(0)">
          <i class="menu-icon icon-apps"></i><span>Suitable Crops Zone</span><i class="accordion-icon fas fa-angle-left"></i>
        </a>
        <ul class="sub-menu" style="display: block;">
          <li class="animation"><a href="#" class="active">Sub1</a></li>
        </ul>
      </li>


      <li class="active-page open">
        <a href="javascript:void(0)">
          <i class="menu-icon icon-apps"></i><span>Crops Zone</span><i class="accordion-icon fas fa-angle-left"></i>
        </a>
        <ul class="sub-menu" style="display: block;">
          <li class="animation"><a href="#" class="active">Sub1</a></li>
        </ul>
      </li>

      <li class="active-page open">
        <a href="javascript:void(0)">
          <i class="menu-icon icon-apps"></i><span>Crops Zone Data</span><i class="accordion-icon fas fa-angle-left"></i>
        </a>
        <ul class="sub-menu" style="display: block;">
          <li class="animation"><a href="#" class="active">Sub1</a></li>
        </ul>
      </li>

      <li class="active-page open">
        <a href="javascript:void(0)">
          <i class="menu-icon icon-apps"></i><span>Agriculture Service</span><i class="accordion-icon fas fa-angle-left"></i>
        </a>
        <ul class="sub-menu" style="display: block;">
          <li class="animation"><a href="#" class="active">Sub1</a></li>
        </ul>
      </li>

      <li class=active-page open>
        <a href="javascript:void(0)">
          <i class="menu-icon icon-layers"></i><span>Live Stock</span><i class="accordion-icon fas fa-angle-left"></i>
        </a>
        <ul class="sub-menu" style="display: none;">
          <li class=""><a href="layout-blank.html">Blank Page</a></li>
          <li class=""><a href="layout-collapsed-sidebar.html">Collapsed Sidebar</a></li>
          <li class=""><a href="layout-fixed-header.html">Fixed Header</a></li>
          <li class=""><a href="layout-fixed-sidebar.html">Fixed Sidebar</a></li>
          <li class=""><a href="layout-fixed-sidebar-header.html">Fixed Sidebar &amp; Header</a></li>
        </ul>
      </li>


      <li class="active-page open">
        <a href="javascript:void(0)">
          <i class="menu-icon icon-apps"></i><span>About</span><i class="accordion-icon fas fa-angle-left"></i>
        </a>
        <ul class="sub-menu" style="display: block;">
          <li class="animation"><a href="#" class="active">Sub1</a></li>
        </ul>
      </li>
    </ul>
  </div><div class="slimScrollBar" style="background: rgb(204, 204, 204); width: 6px; position: absolute; top: 0px; opacity: 0.2; display: none; border-radius: 0px; z-index: 99; right: 0px; height: 312px;"></div><div class="slimScrollRail" style="width: 6px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 0px; background: rgb(51, 51, 51); opacity: 0.2; z-index: 90; right: 0px;"></div></div>
</div>

app/views/shared/_setting_sidebar.html.erb
<div class="settings-sidebar">
  <div class="settings-sidebar-content">
    <div class="settings-sidebar-header">
      <span>Settings</span>
      <a href="javascript: void(0);" class="settings-menu-close"><i class="icon-close"></i></a>
    </div>
    <div class="right-sidebar-settings">
      <span class="settings-title">General Settings</span>
      <ul class="sidebar-setting-list list-unstyled">
        <li>
          <span class="settings-option">Notifications</span><input type="checkbox" class="js-switch" checked="" data-switchery="true" style="display: none;"><span class="switchery switchery-small" style="background-color: rgb(99, 114, 130); border-color: rgb(99, 114, 130); box-shadow: rgb(99, 114, 130) 0px 0px 0px 11px inset; transition: border 0.4s ease 0s, box-shadow 0.4s ease 0s, background-color 1.2s ease 0s;"><small style="left: 13px; background-color: rgb(255, 255, 255); transition: background-color 0.4s ease 0s, left 0.2s ease 0s;"></small></span>
        </li>
        <li>
          <span class="settings-option">Activity log</span><input type="checkbox" class="js-switch" checked="" data-switchery="true" style="display: none;"><span class="switchery switchery-small" style="background-color: rgb(99, 114, 130); border-color: rgb(99, 114, 130); box-shadow: rgb(99, 114, 130) 0px 0px 0px 11px inset; transition: border 0.4s ease 0s, box-shadow 0.4s ease 0s, background-color 1.2s ease 0s;"><small style="left: 13px; background-color: rgb(255, 255, 255); transition: background-color 0.4s ease 0s, left 0.2s ease 0s;"></small></span>
        </li>
        <li>
          <span class="settings-option">Automatic updates</span><input type="checkbox" class="js-switch" data-switchery="true" style="display: none;"><span class="switchery switchery-small" style="box-shadow: rgb(223, 223, 223) 0px 0px 0px 0px inset; border-color: rgb(223, 223, 223); background-color: rgb(255, 255, 255); transition: border 0.4s ease 0s, box-shadow 0.4s ease 0s;"><small style="left: 0px; transition: background-color 0.4s ease 0s, left 0.2s ease 0s;"></small></span>
        </li>
        <li>
          <span class="settings-option">Allow backups</span><input type="checkbox" class="js-switch" data-switchery="true" style="display: none;"><span class="switchery switchery-small" style="box-shadow: rgb(223, 223, 223) 0px 0px 0px 0px inset; border-color: rgb(223, 223, 223); background-color: rgb(255, 255, 255); transition: border 0.4s ease 0s, box-shadow 0.4s ease 0s;"><small style="left: 0px; transition: background-color 0.4s ease 0s, left 0.2s ease 0s;"></small></span>
        </li>
      </ul>
      <span class="settings-title">Account Settings</span>
      <ul class="sidebar-setting-list list-unstyled">
        <li>
          <span class="settings-option">Chat</span><input type="checkbox" class="js-switch" checked="" data-switchery="true" style="display: none;"><span class="switchery switchery-small" style="background-color: rgb(99, 114, 130); border-color: rgb(99, 114, 130); box-shadow: rgb(99, 114, 130) 0px 0px 0px 11px inset; transition: border 0.4s ease 0s, box-shadow 0.4s ease 0s, background-color 1.2s ease 0s;"><small style="left: 13px; background-color: rgb(255, 255, 255); transition: background-color 0.4s ease 0s, left 0.2s ease 0s;"></small></span>
        </li>
        <li>
          <span class="settings-option">Incognito mode</span><input type="checkbox" class="js-switch" data-switchery="true" style="display: none;"><span class="switchery switchery-small" style="box-shadow: rgb(223, 223, 223) 0px 0px 0px 0px inset; border-color: rgb(223, 223, 223); background-color: rgb(255, 255, 255); transition: border 0.4s ease 0s, box-shadow 0.4s ease 0s;"><small style="left: 0px; transition: background-color 0.4s ease 0s, left 0.2s ease 0s;"></small></span>
        </li>
        <li>
          <span class="settings-option">Public profile</span><input type="checkbox" class="js-switch" data-switchery="true" style="display: none;"><span class="switchery switchery-small" style="box-shadow: rgb(223, 223, 223) 0px 0px 0px 0px inset; border-color: rgb(223, 223, 223); background-color: rgb(255, 255, 255); transition: border 0.4s ease 0s, box-shadow 0.4s ease 0s;"><small style="left: 0px; transition: background-color 0.4s ease 0s, left 0.2s ease 0s;"></small></span>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="page-sidebar">
  <div class="profile-menu">
    <a href="#">
      <%= image_tag 'avatars/avatar1.png', alt: "" %>
    </a>
  </div>
  <div class="page-sidebar-inner">
    <div class="page-sidebar-menu">
      <ul>
        <li>
          <a href="#" data-toggle="tooltip" data-placement="right" title="" data-original-title="Dashboard"><i class="fas fa-rocket"></i></a>
        </li>
        <li>
          <a href="#" data-toggle="tooltip" data-placement="right" title="" data-original-title="News"><i class="fas fa-globe-africa"></i></a>
        </li>
        <li>
          <a href="#" data-toggle="tooltip" data-placement="right" title="" data-original-title="Inbox"><i class="fas fa-inbox"></i></a>
        </li>
        <li>
          <a href="#" data-toggle="tooltip" data-placement="right" title="" data-original-title="Chat"><i class="far fa-comments"></i></a>
        </li>
      </ul>
    </div>
  </div>
  <div class="settings-menu-btn">
    <a href="#" class="settings-menu-link"><i class="fas fa-wrench"></i></a>
  </div>
</div><!-- /Page Sidebar -->